# Generated by Django 5.0.7 on 2024-09-08 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_application_callbackrequest_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='feedback',
            field=models.TextField(blank=True, null=True),
        ),
    ]
